apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: hackers
          artifact-id: 9067944b-7793-459b-9a98-edb9f378a6b6
          target-environment: Pre-Prod
